# This file configures your Netlify deploy
# Settings declared here override everything on Dashboard interface
# https://docs.netlify.com/configure-builds/file-based-configuration/
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"