---
spring:
  profiles:
    active: default
  #  datasource:
  #?allowPublicKeyRetrieval=true&useSSL=false
  #    url: jdbc:mysql://localhost:3306/peladator
  #    username: peladator
  #    password: peladator
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: ${PORT:5000}
  servlet:
    context-path: /api
  h2:
    console:
      enabled: true
