---
server:
  port: ${PORT:5000}
  servlet:
    context-path: /api
#  h2:
#    console:
#      enabled: true
#  datasource:
  #?allowPublicKeyRetrieval=true&useSSL=false
#    url: jdbc:mysql://localhost:3306/peladator
#    username: peladator
#    password: peladator
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
