---
api:
  jwt:
    expiration: 86400000
    secret: secret
    token-type: Bearer
    issuer: peladator_api
spring:
  profiles:
    active: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  jackson:
    locale: pt-BR
    time-zone: America/Sao_Paulo

server:
  port: ${PORT:5000}
  servlet:
    context-path: /api
