---
api:
  jwt:
    expiration: 86400000
    secret: secret
    token-type: Bearer
    issuer: peladator API
spring:
  profiles:
    active: dev
  #  datasource:
  #?allowPublicKeyRetrieval=true&useSSL=false
  #    url: jdbc:mysql://localhost:3306/peladator
  #    username: peladator
  #    password: peladator
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jackson:
    locale: pt-BR
    time-zone: America/Sao_Paulo
server:
  port: ${PORT:5000}
  servlet:
    context-path: /api
  h2:
    console:
      enabled: true
logging:
  level:
    com:
      paulrps:
        peladator: DEBUG